# Generated by Django 5.2.4 on 2025-08-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
